*&---------------------------------------------------------------------*
*& Report ZR_ALV_TEST_03
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZR_ALV_TEST_03.

TYPE-POOLS: SLIS. "定义Fieldcat一定要先调用该类型池
*定義FIELDCATと LAYOUT
DATA: FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
      LAYOUT TYPE SLIS_LAYOUT_ALV,
      W_REPID LIKE SY-REPID.

TABLES: SPFLI.
DATA: LSPFLI LIKE STANDARD TABLE OF SPFLI WITH HEADER LINE.

PARAMETERS :
P_CITYFR TYPE SPFLI-CITYFROM,
P_CITYTO TYPE SPFLI-CITYTO.

START-OF-SELECTION.
    PERFORM GETDATA.
    PERFORM CATALOG.
    PERFORM ALVSHOW.

*从透明表中获取数据
FORM GETDATA.
    SELECT * FROM SPFLI
    INTO CORRESPONDING FIELDS OF TABLE LSPFLI
    WHERE CITYFROM = P_CITYFR
    AND CITYTO = P_CITYTO.
ENDFORM.

*Form CATALOG 構造により取得 FIELDCAT
FORM CATALOG.
    W_REPID = SY-REPID.
    CLEAR fieldcat.

    CALL FUNCTION 'REUSE_ALV_FIELDCATALOG_MERGE'
    EXPORTING
        I_PROGRAM_NAME = W_REPID
        I_STRUCTURE_NAME = 'SPFLI'
    CHANGING
        CT_FIELDCAT = FIELDCAT[]
    EXCEPTIONS
        INCONSISTENT_INTERFACE = 1
        PROGRAM_ERROR = 2
        OTHERS = 3.

    IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.

*対FIELDCAT属性的修改
    READ TABLE FIELDCAT INDEX 2.   "将第二列设置为热点显示
    FIELDCAT-HOTSPOT = 'X'.
    MODIFY FIELDCAT INDEX 2.
    READ TABLE FIELDCAT INDEX 4.   "将第四列设置为KEY值字段
    FIELDCAT-KEY = 'X'.
    MODIFY FIELDCAT INDEX 4.
    READ TABLE FIELDCAT INDEX 5.   "将第五列没買力CHECKBOX
    FIELDCAT-CHECKBOX = 'X'.
    MODIFY FIELDCAT INDEX 5.

    LAYOUT-COLWIDTH_OPTIMIZE = 'X'.  "设置Layout 输出格式最优化 ENDFORM.
ENDFORM.

*& Form ALVSHOW  将ALV 报表按GRID 格式显示 FORMALVSHOW.
FORM ALVSHOW.
    CALL FUNCTION'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
        I_CALLBACK_PROGRAM = W_REPID
        IS_LAYOUT = LAYOUT
        I_GRID_TITLE = 'ALV REPORT TEST'
        IT_FIELDCAT = FIELDCAT[]
    TABLES
        T_OUTTAB  = LSPFLI
    EXCEPTIONS
        PROGRAM_ERROR = 1
        OTHERS = 2.

    IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.
ENDFORM.