*&---------------------------------------------------------------------*
*& Report ZR_ALV_TEST_02
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZR_ALV_TEST_02.

TYPE-POOLS: SLIS.
TABLES: SPFLI.
DATA:FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE, 
    LAYOUT TYPE SLIS_LAYOUT_ALV,
    W_REPID LIKE SY-REPID.

DATA: LS_SPFLI TYPE SPFLI.
DATA: LSPFLI LIKE STANDARD TABLE OF LS_SPFLI WITH HEADER LINE.

DATA: L_PERSNUMBER LIKE USR21-PERSNUMBER, 
        L_TEL_EXTENS LIKE ADCPS-TEL_EXTENS.

START-OF-SELECTION. 
PERFORM GETDATA. 
PERFORM CATALOG.
PERFORM ALVSHOW.

* 从数据裘中荻取数据 
FORM GETDATA.
    SELECT * FROM SPFLI
    INTO CORRESPONDING FIELDS OF TABLE LSPFLI. 
ENDFORM.

*定義 Catalog 
FORM CATALOG.
    W_REPID = SY-REPID. 
    CLEAR FIELDCAT.

*定义宏来设置FIELDCAT屆性 
    DEFINE FIELDCATSET.
        FIELDCAT-REF_TABNAME = 'LSPFLI'. 
        FIELDCAT-FIELDNAME = &1. 
        FIELDCAT-SELTEXT_L = &1. 
        FIELDCAT-COL_POS = &2.
        APPEND FIELDCAT. 
    END-OF-DEFINITION.

    FIELDCATSET 'CARRID' SY-TABIX. 
    FIELDCATSET 'CONNID' SY-TABIX.
    FIELDCATSET 'COUNTRYFR' SY-TABIX. 
    FIELDCATSET 'CITYFROM' SY-TABIX. 
    FIELDCATSET 'AIRPFROM' SY-TABIX. 
    FIELDCATSET 'COUNTRYTO' SY-TABIX. 
    FIELDCATSET 'AIRPTO' SY-TABIX. 
    FIELDCATSET'FLTIME' SY-TABIX.
    FIELDCATSET 'DEPTIME' SY-TABIX. 
    FIELDCATSET 'ARRTIME' SY-TABIX. 
    FIELDCATSET 'DISTANCE' SY-TABIX. 
    FIELDCATSET 'DISTID' SY-TABIX. 
    FIELDCATSET 'FLTYPE' SY-TABIX.
    FIELDCATSET 'PERIOD' SY-TABIX.
    LAYOUT-COLWIDTH_OPTIMIZE ='X'. 
ENDFORM.

*出力 ALV
FORM ALVSHOW.
    CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY' 
    EXPORTING
    I_CALLBACK_PROGRAM = W_REPID 
    I_SAVE = ''
    IS_LAYOUT = LAYOUT
    I_GRID_TITLE = 'ALV TEST'
    IT_FIELDCAT = FIELDCAT[]
    TABLES
        T_OUTTAB  = LSPFLI
    EXCEPTIONS
        PROGRAM_ERROR = 1
        OTHERS = 2.
     
   
    IF SY-SUBRC <> 0.
        MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4. 
    ENDIF.
ENDFORM.
